Repository dmno-dev/dmno, pull requests merged in 2024-11, with the labels that each got.

#150 move latest nextjs example into main repo
  example-repo/packages/nextjs-web/.dmno/config.mts
  example-repo/packages/nextjs-web/src/app/api/fetch-dynamic-public-config/route.ts
  example-repo/packages/nextjs-web/src/app/api/route.ts
  example-repo/packages/nextjs-web/src/app/app/api-edge/route.ts
  example-repo/packages/nextjs-web/src/app/app/api-node/route.ts
  example-repo/packages/nextjs-web/src/app/app/client-page/page.tsx
  example-repo/packages/nextjs-web/src/app/app/intercept-allow/page.tsx
  example-repo/packages/nextjs-web/src/app/app/intercept/page.tsx
  example-repo/packages/nextjs-web/src/app/app/leak-client/page.tsx
  example-repo/packages/nextjs-web/src/app/app/page-edge/page.tsx
  example-repo/packages/nextjs-web/src/app/app/page-node/page.tsx
  example-repo/packages/nextjs-web/src/app/app/server-action/action.ts
  example-repo/packages/nextjs-web/src/app/app/server-action/page.tsx
  example-repo/packages/nextjs-web/src/app/fetch-dynamic-public-config/route.ts
  example-repo/packages/nextjs-web/src/app/globals.css
  example-repo/packages/nextjs-web/src/app/helper.ts
  example-repo/packages/nextjs-web/src/app/intercept-test/page.tsx
  example-repo/packages/nextjs-web/src/app/layout.tsx
  example-repo/packages/nextjs-web/src/app/leak-test/page.tsx
  example-repo/packages/nextjs-web/src/app/page.tsx
  example-repo/packages/nextjs-web/src/instrumentation.ts
  example-repo/packages/nextjs-web/src/pages/api/api-edge.ts
  example-repo/packages/nextjs-web/src/pages/api/api-node.ts
  example-repo/packages/nextjs-web/src/pages/api/fetch-dynamic-public-config2.ts
  example-repo/packages/nextjs-web/src/pages/pages/amp.tsx
  example-repo/packages/nextjs-web/src/pages/pages/page-edge.tsx
  example-repo/packages/nextjs-web/src/pages/pages/page-node.tsx
Labels: maintainer

#153 Bugfixes nov 7
  .changeset/breezy-horses-cough.md
  .changeset/mighty-beers-join.md
  .changeset/wild-walls-glow.md
  .dmno/config.mts
  example-repo/.dmno/config.mts
  packages/configraph/src/data-types.ts
  packages/configraph/src/resolvers.ts
  packages/configraph/test/data-types.test.ts
  packages/configraph/test/resolution.test.ts
  packages/core/src/config-engine/type-generation.ts
  packages/core/tsconfigs/dmno-folder.json
  packages/docs-site/src/content/docs/docs/guides/schema.mdx
  packages/docs-site/src/content/docs/docs/reference/helper-methods.mdx
Labels: maintainer

#155 Deprecate `switchByNodeEnv`
  .changeset/silly-rivers-mate.md
  example-repo/packages/api/.dmno/config-example.ts
  example-repo/packages/api/.dmno/config.mts
  example-repo/packages/express-js/.dmno/config.mts
  example-repo/packages/nuxt-web/.dmno/config.mts
  packages/configraph/src/resolvers/switch.ts
  packages/configraph/test/resolution.test.ts
  packages/core/src/cli/lib/init-helpers.ts
  packages/docs-site/src/content/docs/docs/guides/env-files.mdx
  packages/docs-site/src/content/docs/docs/guides/multi-env.mdx
  packages/docs-site/src/content/docs/docs/reference/helper-methods.mdx
Labels: maintainer

#152 Infisical plugin and docs cleanup
  .changeset/angry-shoes-poke.md
  example-repo/.dmno/config.mts
  example-repo/package.json
  example-repo/pnpm-lock.yaml
  packages/docs-site/astro.config.ts
  packages/docs-site/src/content/docs/docs/guides/secret-segmentation.mdx
  packages/docs-site/src/content/docs/docs/plugins/1password.mdx
  packages/docs-site/src/content/docs/docs/plugins/bitwarden.mdx
  packages/docs-site/src/content/docs/docs/plugins/infisical.mdx
  packages/docs-site/src/content/docs/docs/plugins/overview.mdx
  packages/plugins/infisical/.eslintrc.cjs
  packages/plugins/infisical/README.md
  packages/plugins/infisical/package.json
  packages/plugins/infisical/src/constants.ts
  packages/plugins/infisical/src/data-types.ts
  packages/plugins/infisical/src/index.ts
  packages/plugins/infisical/src/plugin.ts
  packages/plugins/infisical/tsconfig.json
  packages/plugins/infisical/tsup.config.ts
  pnpm-lock.yaml
Labels: documentation, enhancement, docs-site, maintainer, plugins/infisical

#157 Vite plugin docs
  .changeset/nine-wolves-travel.md
  packages/docs-site/src/content/docs/docs/integrations/vite.mdx
  packages/integrations/vite/package.json
  pnpm-lock.yaml
Labels: maintainer

#159 allow .env style output from resolve and add associated docs
  .changeset/hungry-terms-cross.md
  packages/core/src/cli/commands/resolve.command.ts
  packages/core/src/cli/lib/env-file-helpers.test.ts
  packages/core/src/cli/lib/env-file-helpers.ts
  packages/core/src/cli/lib/selection-helpers.ts
  packages/core/src/cli/lib/shell-helpers.test.ts
  packages/core/src/cli/lib/shell-helpers.ts
  packages/docs-site/src/content/docs/docs/guides/env-files.mdx
Labels: documentation, enhancement, docs-site, maintainer

#163 nextjs config fixes
  .changeset/gorgeous-chefs-admire.md
  packages/integrations/nextjs/package.json
  packages/integrations/nextjs/src/index.ts
  packages/integrations/nextjs/tsup.config.ts
  pnpm-lock.yaml
Labels: maintainer

#164 shared-dmno-server
  .changeset/fresh-hairs-join.md
  example-repo/.dmno/config.mts
  example-repo/.dmno/prod.vault.json
  example-repo/packages/api/.dmno/config-example.ts
  example-repo/packages/api/package.json
  example-repo/packages/astro-web/astro.config.ts
  package.json
  packages/configraph/package.json
  packages/configraph/src/config-node.ts
  packages/configraph/src/data-types.ts
  packages/configraph/src/errors.ts
  packages/configraph/src/serialization-types.ts
  packages/core/package.json
  packages/core/src/cli/cli-executable.ts
  packages/core/src/cli/commands/clear-cache.command.ts
  packages/core/src/cli/commands/dev.command.ts
  packages/core/src/cli/commands/init.command.ts
  packages/core/src/cli/commands/plugin.command.ts
  packages/core/src/cli/commands/printenv.command.ts
  packages/core/src/cli/commands/resolve.command.ts
  packages/core/src/cli/commands/run.command.ts
  packages/core/src/cli/lib/cache-helpers.ts
  packages/core/src/cli/lib/cli-ctx.ts
  packages/core/src/cli/lib/env-file-helpers.ts
  packages/core/src/cli/lib/formatting.ts
  packages/core/src/cli/lib/init-helpers.ts
  packages/core/src/cli/lib/init-process.ts
  packages/core/src/cli/lib/resolution-context-helpers.ts
  packages/core/src/cli/lib/selection-helpers.ts
  packages/core/src/cli/lib/watch-mode-helpers.ts
  packages/core/src/config-engine/authoring-utils.ts
  packages/core/src/config-engine/check-errors-helpers.ts
  packages/core/src/config-engine/config-engine.ts
  packages/core/src/config-engine/configraph-adapter.ts
  packages/core/src/config-engine/data-types.ts
  packages/core/src/config-engine/dmno-plugin.ts
  packages/core/src/config-engine/type-generation.ts
  packages/core/src/config-loader/config-loader.ts
  packages/core/src/config-loader/config-server-client.ts
  packages/core/src/config-loader/config-server.ts
  packages/core/src/config-loader/dmno-server.ts
  packages/core/src/config-loader/find-services.ts
  packages/core/src/config-loader/ipc-requests.ts
  packages/core/src/config-loader/serialization-types.ts
  packages/core/src/config-loader/vite-server.ts
  packages/core/src/index.ts
  packages/core/src/lib/certs.ts
  packages/core/src/lib/dotenv-utils.ts
  packages/core/src/lib/env-vars.ts
  packages/core/src/lib/uws-utils.ts
  packages/core/tsup.config.ts
  packages/dev-ui/src/components/graph/ConfigNode.vue
  packages/integrations/astro/src/index.ts
  packages/integrations/remix/src/index.ts
  packages/integrations/vite/src/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: maintainer

#156 nov 8 bug reports
  .changeset/clean-wolves-complain.md
  .changeset/grumpy-hats-kneel.md
  packages/configraph/src/data-types.ts
  packages/configraph/test/data-types.test.ts
  packages/core/src/config-engine/check-errors-helpers.ts
  packages/core/src/config-engine/config-engine.ts
Labels: maintainer

#168 fix plugin input defaults behaviour
  .changeset/nervous-dingos-double.md
  packages/configraph/src/resolvers.ts
  packages/configraph/src/resolvers/injection.ts
  packages/configraph/test/data-types.test.ts
  packages/plugins/1password/src/plugin.ts
Labels: maintainer

#167 turbo and monorepo guide
  example-repo/package.json
  example-repo/pnpm-lock.yaml
  example-repo/turbo.json
  package.json
  packages/docs-site/astro.config.ts
  packages/docs-site/src/content/docs/docs/guides/monorepos.mdx
  packages/docs-site/src/content/docs/docs/guides/repo.mdx
  packages/docs-site/src/style/global.less
Labels: maintainer

#166 improve warning handling
  .changeset/soft-eyes-stare.md
  example-repo/packages/dmno-ui-demo/.dmno/config.mts
  packages/configraph/src/config-node.ts
  packages/core/src/cli/lib/formatting.ts
  packages/core/src/config-engine/check-errors-helpers.ts
Labels: maintainer

#170 fix 1pass service account, add timing debug
  .changeset/old-adults-divide.md
  packages/plugins/1password/package.json
  packages/plugins/1password/src/plugin.ts
  pnpm-lock.yaml
Labels: maintainer
