Repository dmno-dev/dmno, pull requests merged in 2024-12, with the labels that each got.

#172 small fixes nov 26
  .changeset/calm-gifts-laugh.md
  packages/core/src/cli/commands/resolve.command.ts
  packages/core/src/config-loader/dmno-server.ts
Labels: maintainer

#174 fastify integration
  .changeset/good-vans-hide.md
  example-repo/packages/fastify/.dmno/config.mts
  example-repo/packages/fastify/.dmno/tsconfig.json
  example-repo/packages/fastify/package.json
  example-repo/packages/fastify/src/dmno-env.d.ts
  example-repo/packages/fastify/src/index.ts
  example-repo/packages/fastify/tsconfig.json
  example-repo/pnpm-lock.yaml
  packages/core/src/cli/lib/init-helpers.ts
  packages/core/src/cli/lib/schema-scaffold.ts
  packages/core/src/config-engine/config-engine.ts
  packages/core/src/config-engine/type-generation.ts
  packages/core/src/globals-injector/injector.ts
  packages/core/src/lib/redaction-helpers.ts
  packages/docs-site/astro.config.ts
  packages/docs-site/src/content/docs/docs/integrations/fastify.mdx
  packages/docs-site/src/content/docs/docs/integrations/overview.mdx
  packages/docs-site/src/pages/docs/index.astro
  packages/integrations/fastify/.eslintrc.cjs
  packages/integrations/fastify/README.md
  packages/integrations/fastify/dmno.meta.json
  packages/integrations/fastify/package.json
  packages/integrations/fastify/src/index.ts
  packages/integrations/fastify/tsconfig.json
  packages/integrations/fastify/tsup.config.ts
  pnpm-lock.yaml
Labels: maintainer

#151 Override loader system
  .changeset/breezy-horses-cough.md
  .changeset/chatty-dots-invite.md
  .changeset/mighty-beers-join.md
  example-repo/.dmno/config.mts
  example-repo/packages/api/.dmno/config.mts
  example-repo/packages/dmno-ui-demo/.dmno/config.mts
  packages/configraph/package.json
  packages/configraph/src/config-node.ts
  packages/configraph/src/errors.ts
  packages/configraph/src/graph.ts
  packages/configraph/src/plugin.ts
  packages/configraph/src/resolvers.ts
  packages/core/package.json
  packages/core/src/config-engine/config-engine.ts
  packages/core/src/config-engine/overrides.ts
  packages/core/src/index.ts
  packages/core/src/lib/async-utils.ts
  packages/core/src/lib/dotenv-utils.ts
  packages/core/src/lib/exec-helpers.ts
  packages/core/src/lib/exec-utils.ts
  packages/core/src/lib/git-utils.ts
  packages/core/src/utils.ts
  packages/core/tsup.config.ts
  packages/docs-site/src/content/docs/docs/guides/typescript.mdx
  packages/plugins/1password/src/cli-helper.ts
  packages/plugins/1password/src/constants.ts
  packages/plugins/1password/src/data-types.ts
  packages/plugins/1password/src/index.ts
  packages/plugins/1password/src/override-loader.ts
  packages/plugins/1password/src/plugin.ts
  packages/ts-lib/src/defer-promise.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: maintainer

#177 add tea.yaml
  tea.yaml
Labels: maintainer

#178 1pass-tweaks
  .changeset/orange-jars-talk.md
  .changeset/six-mails-remain.md
  example-repo/.dmno/config.mts
  packages/plugins/1password/src/cli-helper.ts
  packages/plugins/1password/src/override-loader.ts
  packages/plugins/1password/src/plugin.ts
Labels: maintainer

#176 Update base-types.mdx: Enum --> enum
  .changeset/nine-spoons-share.md
  packages/docs-site/src/content/docs/docs/reference/base-types.mdx
Labels: maintainer

#181 fix: race condition with picked nodes
  .changeset/rare-zebras-cheer.md
  packages/configraph/src/resolvers/pick.ts
  packages/configraph/test/pick.test.ts
Labels: maintainer

#182 introduce `includeInDmnoConfig` option
  .changeset/few-rings-nail.md
  example-repo/packages/astro-web/.dmno/config.mts
  packages/core/src/cli/commands/printenv.command.ts
  packages/core/src/cli/commands/resolve.command.ts
  packages/core/src/cli/commands/run.command.ts
  packages/core/src/config-engine/config-engine.ts
  packages/core/src/config-engine/configraph-adapter.ts
  packages/core/src/config-engine/type-generation.ts
  packages/core/src/config-loader/dmno-server.ts
  packages/integrations/astro/src/index.ts
  packages/integrations/remix/src/index.ts
  packages/integrations/vite/src/index.ts
  packages/plugins/1password/src/data-types.ts
  packages/plugins/bitwarden/src/data-types.ts
  packages/plugins/encrypted-vault/src/data-types.ts
  packages/plugins/infisical/src/data-types.ts
Labels: maintainer

#175 refactor types w/ instance options system
  .changeset/twenty-ladybugs-yawn.md
  packages/configraph/src/config-node.ts
  packages/configraph/src/data-types.ts
  packages/configraph/src/resolvers.ts
  packages/configraph/test/data-types.test.ts
  packages/configraph/test/resolution.test.ts
  packages/core/src/vendor-types/git.vendor-types.ts
Labels: maintainer

#180 use node https instead of uwebsockets
  packages/core/package.json
  packages/core/src/cli/lib/init-helpers.ts
  packages/core/src/cli/lib/init-process.ts
  packages/core/src/config-loader/dmno-server.ts
  packages/core/src/lib/uws-utils.ts
  packages/core/src/lib/web-server-utils.ts
  pnpm-lock.yaml
Labels: maintainer

#183 make switchBy work with non string values
  .changeset/silly-students-talk.md
  packages/configraph/src/resolvers/switch.ts
  packages/configraph/test/resolution.test.ts
Labels: maintainer

#161 First version of @dmno/cloudflare-platform
  .changeset/soft-terms-try.md
  .dmno/config.mts
  packages/core/package.json
  packages/core/src/config-engine/authoring-utils.ts
  packages/core/src/config-loader/vite-server.ts
  packages/core/src/globals-injector/auto-inject.ts
  packages/core/tsup.inject-standalone.config.ts
  packages/docs-site/astro.config.ts
  packages/docs-site/public/_redirects
  packages/docs-site/src/components/EmailSignup.vue
  packages/docs-site/src/content/docs/docs/guides/typescript.mdx
  packages/docs-site/src/content/docs/docs/platforms/cloudflare.mdx
  packages/docs-site/src/content/docs/docs/platforms/overview.mdx
  packages/integrations/astro/src/index.ts
  packages/integrations/nextjs/src/index.ts
  packages/integrations/remix/src/index.ts
  packages/platforms/cloudflare/.eslintrc.cjs
  packages/platforms/cloudflare/README.md
  packages/platforms/cloudflare/package.json
  packages/platforms/cloudflare/src/data-types.ts
  packages/platforms/cloudflare/src/dwrangler.ts
  packages/platforms/cloudflare/src/index.ts
  packages/platforms/cloudflare/tsconfig.json
  packages/platforms/cloudflare/tsup.config.ts
  packages/signup-api/.dmno/config.mts
  packages/signup-api/.gitignore
  packages/signup-api/functions-src/dmno-env.d.ts
  packages/signup-api/functions-src/lib/mailerlite.ts
  packages/signup-api/functions-src/signup.ts
  packages/signup-api/functions-src/types/emailvalid.d.ts
  packages/signup-api/functions/README.md
  packages/signup-api/netlify.toml
  packages/signup-api/package.json
  packages/signup-api/public/_routes.json
  packages/signup-api/src/endpoints/signup.ts
  packages/signup-api/src/lib/mailerlite.ts
  packages/signup-api/tsconfig.json
  packages/signup-api/tsup.config.ts
  packages/signup-api/wrangler.toml
  pnpm-lock.yaml
Labels: maintainer

#184 some cloudflare copy cleanup
  packages/docs-site/src/content/docs/docs/platforms/cloudflare.mdx
Labels: documentation, docs-site, maintainer

#171 WIP new animated graph on homepage
  packages/dev-ui/src/components/layout/HeaderBar.vue
  packages/docs-site/.eslintrc.cjs
  packages/docs-site/astro.config.ts
  packages/docs-site/package.json
  packages/docs-site/postcss.config.cjs
  packages/docs-site/public/_redirects
  packages/docs-site/src/components/CTABlock.astro
  packages/docs-site/src/components/CustomStarlightBanner.astro
  packages/docs-site/src/components/CustomStarlightHeader.astro
  packages/docs-site/src/components/EmailSignup.vue
  packages/docs-site/src/components/Hero.astro
  packages/docs-site/src/components/LandingPageSection.astro
  packages/docs-site/src/components/LogoBar.astro
  packages/docs-site/src/components/ThemeSelect.vue
  packages/docs-site/src/components/TileButton.vue
  packages/docs-site/src/components/homepage/ConfigExample.astro
  packages/docs-site/src/components/homepage/IntegrationTile.vue
  packages/docs-site/src/components/homepage/IntegrationsHero.vue
  packages/docs-site/src/components/homepage/config-example.ts
  packages/docs-site/src/components/layouts/LandingPage.astro
  packages/docs-site/src/components/mailerlite/SignUp.astro
  packages/docs-site/src/content/docs/docs/get-started/quickstart.mdx
  packages/docs-site/src/pages/_drafts/docs-home.astro
  packages/docs-site/src/pages/docs/index.astro
  packages/docs-site/src/pages/index.astro
  packages/docs-site/src/style/global.less
  packages/docs-site/tsconfig.json
  packages/ui-lib/src/components/DmnoTileLogo.vue
  packages/ui-lib/src/components/DotsLoader.vue
  pnpm-lock.yaml
Labels: documentation, docs-site, maintainer

#186 add auto labeler and associated config
  .github/config/labeler.yaml
  .github/workflows/pr-labeler.yaml
Labels: maintainer

#187 logs cleanup for dwrangler
  .changeset/purple-zebras-vanish.md
  packages/docs-site/src/content/docs/docs/platforms/netlify.mdx
  packages/platforms/cloudflare/src/dwrangler.ts
Labels: maintainer

#185 clean up and standardize READMEs
  .changeset/warm-tools-raise.md
  README.md
  packages/configraph/README.md
  packages/core/README.md
  packages/docs-site/README.md
  packages/integrations/astro/README.md
  packages/integrations/fastify/README.md
  packages/integrations/nextjs/README.md
  packages/integrations/remix/README.md
  packages/integrations/vite/README.md
  packages/platforms/cloudflare/README.md
  packages/platforms/netlify/README.md
  packages/platforms/vercel/README.md
  packages/plugins/1password/README.md
  packages/plugins/bitwarden/README.md
  packages/plugins/encrypted-vault/README.md
  packages/plugins/infisical/README.md
Labels: documentation, docs-site, integrations/astro, integrations/nextjs, integrations/vite, plugins/1password, plugins/encrypted-vault, integrations/remix, maintainer, plugins/infisical, plugins/bitwarden, integrations/fastify, platforms/netlify, platforms/vercel, platforms/cloudflare
