Repository dmno-dev/dmno, pull requests merged in 2025-04, with the labels that each got.

#217 override loader docs
  .changeset/config.json
  package.json
  packages/docs-site/astro.config.ts
  packages/docs-site/src/content/docs/docs/guides/env-files.mdx
  packages/docs-site/src/content/docs/docs/guides/overrides.mdx
  packages/docs-site/src/content/docs/docs/plugins/1password.mdx
  pnpm-lock.yaml
Labels: docs-site, maintainer

#218 Fixed a code snippet error in schema guide
  packages/docs-site/src/content/docs/docs/guides/schema.mdx
Labels: community

#219 1pass blog post
  packages/docs-site/src/assets/blog/1pass/dmno-1password.png
  packages/docs-site/src/assets/blog/1pass/enable-cli.png
  packages/docs-site/src/assets/blog/1pass/env-blob.png
  packages/docs-site/src/content/docs/blog/safer-secrets-with-1pass.md
Labels: maintainer

#222 add turbopack warning
  packages/docs-site/src/content/docs/docs/integrations/nextjs.mdx
Labels: maintainer
